// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace HomePageScssNamespace {
  export interface IHomePageScss {
    active: string;
    back: string;
    front: string;
    tile: string;
    tileInside: string;
  }
}

declare const HomePageScssModule: HomePageScssNamespace.IHomePageScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HomePageScssNamespace.IHomePageScss;
};

export = HomePageScssModule;
