// Automatically generated by @teamsupercell/typings-for-css-modules-loader.
// Please do not edit this file manually.
declare namespace AppScssNamespace {
  export interface IAppScss {
    app: string;
    error: string;
    errorInfo: string;
  }
}

declare const AppScssModule: AppScssNamespace.IAppScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AppScssNamespace.IAppScss;
};

export = AppScssModule;
