/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const themeLight: string;
const themeDark: string;
const app: string;
const error: string;
const errorInfo: string;

export {
	themeLight,
	themeDark,
	app,
	error,
	errorInfo
};

export default {
	"theme-light": themeLight,
	themeLight,
	"theme-dark": themeDark,
	themeDark,
	app,
	error,
	errorInfo
};
