/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const app: string;

export {
	app
};

declare const __default_export__: {
	app: typeof app;
};
export default __default_export__;
