/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const themeLight: string;
const themeDark: string;
const header: string;
const themeToggle: string;
const gitHubLink: string;
const headerButtons: string;

export {
	themeLight,
	themeDark,
	header,
	themeToggle,
	gitHubLink,
	headerButtons
};

export default {
	"theme-light": themeLight,
	themeLight,
	"theme-dark": themeDark,
	themeDark,
	header,
	themeToggle,
	gitHubLink,
	headerButtons
};
