/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const header: string;
declare const themeToggle: string;
declare const gitHubLink: string;
declare const headerButtons: string;

export {
	header,
	themeToggle,
	gitHubLink,
	headerButtons
};

declare const __default_export__: {
	header: typeof header;
	themeToggle: typeof themeToggle;
	gitHubLink: typeof gitHubLink;
	headerButtons: typeof headerButtons;
};
export default __default_export__;
