/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const linksList: string;

export {
	linksList
};

declare const __default_export__: {
	linksList: typeof linksList;
};
export default __default_export__;
